#!/usr/bin/env bun

/**
 * Sync version from package.json into src/version.ts
 * Run this before builds or after version bumps to keep the version in sync.
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const root = resolve(import.meta.dir, "..");
const pkg = JSON.parse(readFileSync(resolve(root, "package.json"), "utf-8"));
const version: string = pkg.version;

const versionFile = resolve(root, "src/version.ts");
const content = `// Auto-generated by scripts/sync-version.ts — do not edit manually\nexport const VERSION = "${version}";\n`;

writeFileSync(versionFile, content, "utf-8");
console.log(`✓ Synced version to ${version}`);
